### ISSUE TITLE
Question about generating shapenet data 

### ISSUE THREAD

**Issue by Jeffwang87** [JRyanShue/NFD#7]
Hi,

Thanks for sharing the code! I wonder where did you convert meshes from the ShapeNet dataset into watertight meshes in your code base

**Comment by yifanjiang19** [comment]
Same question

**Comment by JRyanShue** [comment]
Sorry for the late response! We used the code from here: https://github.com/autonomousvision/occupancy_networks/tree/master/external/mesh-fusion

It's a pretty big pain to do the watertighting, so here are some download links for the watertight meshes:
* Cars (~79G): https://imt-public-datasets.s3.amazonaws.com/watertight_shapenet_cars.zip
* Chairs (~15.9G): https://imt-public-datasets.s3.amazonaws.com/watertight_meshes/03001627_3_fused.zip
* Planes (~4G): https://imt-public-datasets.s3.amazonaws.com/watertight_shapenet/watertight_shapenet_planes.zip

Compressed files wjll be available soon.

**Comment by FrederikWarburg** [comment]
Thanks for sharing this. The last link doesn't seem to work.

**Comment by JRyanShue** [comment]
Hm, it works on my end. What's the error message you're getting?

**Comment by FrederikWarburg** [comment]
Works now! Thanks again :)
